#!/bin/sh

#
# GQ: Get user data
#

# Modify this line to specify filename
file=/tmp/userdata

# Get DomR Ip
i=1
while [ $i -le 5 ];do
    DOMR_IP=$(netstat -nr|grep default|awk '{print $2}')
    if [ -n "$DOMR_IP" ]; then
        break;
    fi
    if [ $x -eq 5 ]; then
        echo "DomR IP address not found. Exiting."
        exit 1
    fi
    sleep 2
    i=$i+1
done

# Get userdata 
userdata=$(/usr/local/bin/wget -t 3 -T 20 -O - http://$DOMR_IP/latest/user-data 2>/dev/null)

if [ $? -ne 0 ]; then
    echo "No userdata found."
    exit 1
fi

echo "$userdata" > $file
head -1 $file|egrep '^#!' 2>&1 > /dev/null

if [ $? -eq 0 ]; then
    chmod 700 $file
    $file
fi

exit 0

