#!/bin/bash

#
# GQ: Get SSH keys for user
#

. /usr/local/qstack/etc/gq-common-funcs

# Modify this line to specify the user (default is root)
user=root

# Get router/dhcp server IP. The weird quote structure for get_domr_ip
# function is needed to embed the value in single quotes.
DHCP_DIR=$(find_dhcp_lease_file)
DOMR_IP=$(get_domr_ip ''"$DHCP_DIR"'')

if [[ "$DOMR_IP" == "" ]]; then
    echo "Could not find DOMR_IP. Exiting."
    exit 1
fi

# Get ssh public key
homedir=$(grep ^$user /etc/passwd|awk -F ":" '{print $6}')
sshdir=$homedir/.ssh
authorized=$sshdir/authorized_keys
publickey=$(wget -t 3 -T 20 -O - http://$DOMR_IP/latest/public-keys 2>/dev/null)

if [ $? -ne 0 ]; then
    echo "Error receiving SSH public key. Exiting."
    exit 1
fi

if [ ! -e $sshdir ]; then
    mkdir $sshdir
fi

if [ ! -e $authorized ]; then
    touch $authorized
fi

otherkeys=$(cat $authorized|grep -v "$publickey")
echo "$otherkeys" > $authorized
echo "$publickey" >> $authorized

exit 0
