#!/bin/sh

#
# GQ: Get passwd for user
#

# Modify this line to specify the user (default is root)
user=root


# Get DomR Ip
for x in $(seq 1 5); do
    DOMR_IP=$(pr_routes |awk '/0.0.0.0/ {print $4}') 
    if [ -n "$DOMR_IP" ]; then
        break;
    fi
    if [ $x -eq 5 ]; then
        echo "DomR IP address not found. Exiting."
        exit 1
    fi
    sleep 2
done

# Get passwd
password=$(curl --retry 3 --retry-delay 20 -o - --header "DomU_Request: send_my_password" $DOMR_IP:8080 2>/dev/null)
if [ $? -ne 0 ]; then
    echo "Error receiving passwd. Exiting."
    exit 1
fi

password=$(echo $password | tr -d '\r')
if [ "$password" = "bad_request" ]; then
    echo "Error receiving passwd; bad request. Exiting."
    exit 1
fi

if [ "$password" != "saved_password" ]; then
    echo $password | passwd --stdin $user 2>/dev/null
    if [ $? -gt 0 ]; then
        sed s:#PASSWD#:$(/usr/sbin/crypt_pw $password):g /etc/master.passwd > /tmp/master.passwd
        mv /tmp/master.passwd /etc/master.passwd
        pwd_mkdb -p /etc/master.passwd
        if [ $? -gt 0 ]; then
            echo "Error saving passwd. Exiting."
            exit 1
        fi
    fi
    curl --retry 3 --retry-delay 20 -o - --header "DomU_Request: saved_password" $DOMR_IP:8080 2>/dev/null
fi
