#!/bin/bash
#
# GQ: Get password for user
#

# Modify this line to specify the user (default is root)
user=ubuntu


# Get DomR Ip
for x in $(seq 1 5); do
    DOMR_IP=$(route -n|awk '/^0.0.0.0/ {print $2}')
    if [ -n "$DOMR_IP" ]; then
        break;
    fi
    if [ $x -eq 5 ]; then
        echo "DomR IP address not found. Exiting."
        exit 1
    fi
    sleep 2
done

# Get passwd
password=$(wget --quiet -t 3 -T 20 -O - --header "DomU_Request: send_my_password" $DOMR_IP:8080 2>/dev/null)
if [ $? -ne 0 ]; then
    echo "Error receiving passwd. Exiting."
    exit 1
fi

password=$(echo $password | tr -d '\r')
if [ "$password" = "bad_request" ]; then
    echo "Error receiving passwd; bad request. Exiting."
    exit 1
fi

if [ "$password" != "saved_password" ]; then
    echo $password | passwd --stdin $user 2>/dev/null
    if [ $? -gt 0 ]; then
        echo $user:$password|chpasswd
        if [ $? -gt 0 ]; then
            echo "Error saving passwd. Exiting."
            exit 1
        fi
    fi
    wget -t 3 -T 20 -O - --header "DomU_Request: saved_password" $DOMR_IP:8080 2>/dev/null
fi
