#!/bin/sh

#
# GQ: Get SSH keys for user
#

# Modify this line to specify the user (default is root)
user=root

# Get DomR Ip
i=1
while [ $i -le 5 ];do
    DOMR_IP=$(netstat -nr|grep default|awk '{print $2}')
    if [ -n "$DOMR_IP" ]; then
        break;
    fi
    if [ $x -eq 5 ]; then
        echo "DomR IP address not found. Exiting."
        exit 1
    fi
    sleep 2
    i=$i+1
done

# Get ssh public key
homedir=$(cat /etc/master.passwd | grep ^$user | awk -F ":" '{print $9}')
sshdir=$homedir/.ssh
authorized=$sshdir/authorized_keys
publickey=$(/usr/local/bin/wget -t 3 -T 20 -O - http://$DOMR_IP/latest/public-keys 2>/dev/null)

if [ $? -ne 0 ]; then
    echo "Error receiving SSH public key. Exiting."
    exit 1
fi

if [ ! -e $sshdir ]; then
    mkdir $sshdir
fi

if [ ! -e $authorized ]; then
    touch $authorized
fi

otherkeys=$(cat $authorized|grep -v "$publickey")
echo "$otherkeys" > $authorized
echo "$publickey" >> $authorized

exit 0

