#!/bin/bash

ln -s /etc/rc.d/gq-create-ssh-keys /etc/rc.d/rc3.d/S50gq-create-ssh-keys
ln -s /etc/rc.d/gq-create-ssh-keys /etc/rc.d/rc5.d/S50gq-create-ssh-keys

ln -s /etc/rc.d/gq-get-passwd /etc/rc.d/rc3.d/S50gq-get-passwd
ln -s /etc/rc.d/gq-get-passwd /etc/rc.d/rc5.d/S50gq-get-passwd

ln -s /etc/rc.d/gq-get-ssh-keys /etc/rc.d/rc3.d/S50gq-get-ssh-keys 
ln -s /etc/rc.d/gq-get-ssh-keys /etc/rc.d/rc5.d/S50gq-get-ssh-keys

ln -s /etc/rc.d/gq-get-userdata /etc/rc.d/rc3.d/S50gq-get-userdata
ln -s /etc/rc.d/gq-get-userdata /etc/rc.d/rc5.d/S50gq-get-userdata

echo "Done!"

exit 0
